# Generated by Django 2.2.1 on 2019-06-13 04:52

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='boards/images'),
            preserve_default=False,
        ),
    ]
