# Generated by Django 2.2.1 on 2019-06-13 05:46

import boards.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190613_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=boards.models.board_image_path),
            preserve_default=False,
        ),
    ]
