# Generated by Django 2.2.1 on 2019-06-13 05:58

import boards.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image_thumbnail',
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=boards.models.board_image_path),
        ),
    ]
